#! /bin/bash

if [ -e "build" ]; then
   echo "Deleting old build directory..."
   rm -r "build"
fi
echo "Creating new build directory..."
mkdir "build"
echo "Copying resource files..."
for i in `cat buildinfo/recList`; do cp -v $i build; done
SOURCE="@buildinfo/buildlist"

echo "Compiling..."
javac -version -d "build" $SOURCE 2>buildmsgs.txt
cat buildmsgs.txt

