/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package recipejar.event;

import java.util.ArrayList;

/**
 * Provides a standardized object to attach a listener to.
 * Typical usage: All application events are fired against the ApplicationEventSource, 
 * so that all the actions generated by a component or sub-components can be sent
 * to a centralized clearing house which handles all the events.
 * 
 * @author james
 */
public class ApplicationEventSource {
   private ArrayList<ApplicationEventListener> appListeners = new ArrayList<ApplicationEventListener>();
   
   public void fireApplicationEvent(ApplicationEvent evt){
    for(int i=0; i<appListeners.size(); i++){
       appListeners.get(i).onEvent(evt);
    }
   }
   
   public void addApplicationEventListener(ApplicationEventListener a){
      appListeners.add(a);
   }
   
   public void removeApplicationEventListener(ApplicationEventListener a){
      appListeners.remove(a);
   }
}
