/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilePrefPanel.java
 *
 * Created on Jul 17, 2011, 10:16:56 AM
 */
package recipejar.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import recipejar.data.Prefs;

/**
 *
 * @author james
 */
public class FilePrefPanel extends javax.swing.JPanel {

   private static JFileChooser fc;
   private ActionListener ac = new ActionListener() {

      public void actionPerformed(ActionEvent e) {
         if (e.getID() == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            Prefs loc;
            if (f.getAbsolutePath().contains(Prefs.DIR_PROGRAM.toString())) {
               int i = f.getAbsolutePath().indexOf(Prefs.DIR_PROGRAM.toString());
               i = i + Prefs.DIR_PROGRAM.toString().length();
               jTextField1.setText(f.getAbsolutePath().substring(i));
               boundPref.set(f.getAbsolutePath().substring(i));
               fc.removeActionListener(ac);
            } else {
               jTextField1.setText(f.getPath());
               boundPref.set(f.getPath());
               fc.removeActionListener(ac);
            }
         }
      }
   };
   private Prefs boundPref;

   public Prefs getBoundPref() {
      return boundPref;
   }

   public void setBoundPref(Prefs boundPref) {
      this.boundPref = boundPref;
   }

   /** Creates new form FilePrefPanel */
   public FilePrefPanel() {
      initComponents();
   }

   public static void setFileChooser(JFileChooser c) {
      fc = c;
   }

   private void checkFileIntegrity() {
      if (!(new File(Prefs.DIR_PROGRAM.toString() + jTextField1.getText())).exists()
              && !(new File(jTextField1.getText())).exists()) {
         JOptionPane.showMessageDialog(this, "File: " + jTextField1.getText() + " does not exist!", "Whoops!", JOptionPane.ERROR_MESSAGE);
         jTextField1.setText(boundPref.toString());
      }
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                onFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        add(jTextField1, gridBagConstraints);

        jButton1.setText("Browse...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBrowse(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        add(jButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void onBrowse(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBrowse
       if (fc != null) {
          fc.setMultiSelectionEnabled(false);
          fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
          fc.setSelectedFile(new File(Prefs.DIR_RESOURCE.toString() + jTextField1.getText()));
          fc.addActionListener(ac);
       }
    }//GEN-LAST:event_onBrowse

    private void onFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_onFocusLost
       checkFileIntegrity();
    }//GEN-LAST:event_onFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
