#! /bin/bash

APPNAME="default"
if [ $1 ] && [ $1 != "clean" ]; then
   APPNAME=$1
fi
#if ! test -e "$APPNAME.app" || ([ $1 ] && [ $1 == "clean" ] ) || [ $2 ]; then
#   cmds/buildjar $APPNAME $2
#fi

if [ -e "$APPNAME.app" ]; then
   echo "Deleting old app..."
   rm -r "$APPNAME.app"
fi
mkdir -pv $APPNAME.app/Contents/Resources/Java
mkdir -v $APPNAME.app/Contents/MacOS
cp -v /System/Library/Frameworks/JavaVM.framework/Versions/Current/Resources/MacOS/JavaApplicationStub $APPNAME.app/Contents/MacOS
cp -v Info.plist $APPNAME.app/Contents
cp -v PkgInfo $APPNAME.app/Contents/MacOS
cp -v $APPNAME.icns $APPNAME.app/Contents/Resources
cp -v $APPNAME.jar $APPNAME.app/Contents/Resources/Java
SetFile -a B $APPNAME.app
